name: 'Add field option to Height App'
description: 'Add field option to Height App'
inputs:
  field:  # id of the field to add option
    description: 'Field ID to add an option'
    required: true
  option:
    description: 'Option to add'
    required: true
outputs:
  status:
    description: 'Status of the action'
runs:
  using: 'node16'
  main: 'index.js'
