name: "Add field option to Height App"
on:
  push:
    branches: [ main ]
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add field option to Height App
        id: create-milestone
        uses: ./
        with:
          field: 3c4ca512-2c67-4163-853d-536c52b59969
          option: 'option 1'
        env:
          HEIGHT_API_KEY: ${{ secrets.HEIGHT_API_KEY }}
